spring.application.name=finance-tracker

# MongoDB Altas
spring.data.mongodb.uri=mongodb+srv://finuser:REMOVED_SECRET@cluster0.exkzvk1.mongodb.net/finance_db?retryWrites=true&w=majority

# spring.data.mongodb.uri=mongodb://localhost:27017/finance_db


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

spring.webmvc.cors.allowed-origins=http://localhost:5173
spring.webmvc.cors.allowed-methods=*
spring.webmvc.cors.allowed-headers=*